version: "3.8"

services:
  kong:
    container_name: kong
    image: kong:alpine
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    command: kong start
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/opt/kong/kong.yml
    volumes:
      - ./kong.yml:/opt/kong/kong.yml

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-root}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-123456}

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=pokorny
    depends_on:
      - user-postgres
      - map-postgres
      - company-postgres
      - unit-postgres
      - log-postgres

  user-postgres:
    image: postgres:14
    container_name: user-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${USER_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${USER_POSTGRES_PASSWORD:-123456}
    volumes:
      - user-postgres:/var/lib/postgresql/data

  map-postgres:
    image: postgres:14
    container_name: map-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${MAP_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${MAP_POSTGRES_PASSWORD:-123456}
    volumes:
      - map-postgres:/var/lib/postgresql/data

  company-postgres:
    image: postgres:14
    container_name: company-postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${COM_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${COM_POSTGRES_PASSWORD:-123456}
    volumes:
      - company-postgres:/var/lib/postgresql/data

  unit-postgres:
    image: postgres:14
    container_name: unit-postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${UNIT_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${UNIT_POSTGRES_PASSWORD:-123456}
    volumes:
      - unit-postgres:/var/lib/postgresql/data

  log-postgres:
    image: postgres:14
    container_name: log-postgres
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${LOG_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${LOG_POSTGRES_PASSWORD:-123456}
    volumes:
      - log-postgres:/var/lib/postgresql/data

  cfg-postgres:
    image: postgres:14
    container_name: cfg-postgres
    restart: always
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=${CFG_POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${CFG_POSTGRES_PASSWORD:-123456}
    volumes:
      - cfg-postgres:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
    name: rabbitmq
  user-postgres:
    name: user-postgres-db
  map-postgres:
    name: map-postgres-db
  company-postgres:
    name: company-postgres-db
  unit-postgres:
    name: unit-postgres-db
  log-postgres:
    name: log-postgres-db
  cfg-postgres:
    name: cfg-postgres-db
